classDiagram
    Animal <|-- Duck
    Animal <|-- Fish
    Animal <|-- Dog
    Animal <|-- Cat
    Animal <|-- Snake
    Animal : +int age
    Animal : +String gender
    Animal: +isMammal()
    Animal: +mate()
    class Duck{
      +String beakColor
      +swim()
      +quack()
    }
    class Fish{
      -int sizeInFeet
      -canEat()
    }
    class Dog{
      +String breed
      +String furColor
      +bark()
      +fetch()
      +wagTail()
    }
    class Cat{
      +String eyeColor
      +boolean isIndoor
      +meow()
      +purr()
      +scratch()
    }
    class Snake{
      +float length
      +boolean isVenomous
      +hiss()
      +shed()
      +slither()
    }